---
name: Filesys-Virtual-Async-Dispatcher
version: 0.01
author:
  - 'Apocalypse <APOCAL@cpan.org>'
abstract: Mounting multiple FsV objects in a single filesystem made possible
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Errno: 0
  Fcntl: 0
  File::Spec: 0
  Filesys::Virtual::Async: 0
build_requires:
  Test::More: 0.86
dynamic_config: 0
provides:
  Filesys::Virtual::Async::Dispatcher:
    file: lib/Filesys/Virtual/Async/Dispatcher.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
